//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart_Product_Mapping
    {
        public int Id { get; set; }
        public Nullable<System.Guid> CartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quatity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpadatedDate { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Product Product { get; set; }
    }
}
