//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> CartId { get; set; }
        public Nullable<int> ShippingId { get; set; }
        public Nullable<decimal> PaymentReceived { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual Shipping Shipping { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
