//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingStatu
    {
        public int Id { get; set; }
        public Nullable<int> ShippingId { get; set; }
        public Nullable<System.DateTime> StatusDateTime { get; set; }
    
        public virtual Shipping Shipping { get; set; }
    }
}
